# Generated by Django 4.0.4 on 2022-05-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Product list',
                'verbose_name_plural': 'Products lists',
            },
        ),
        migrations.AlterModelOptions(
            name='homeslider',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Home slides'},
        ),
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerse.productslist')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Products categories',
            },
        ),
    ]
