# Generated by Django 4.0.4 on 2022-05-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse', '0002_productslist_alter_homeslider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerse.productscategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productscategory',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
