# Generated by Django 4.0.4 on 2022-05-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscategory',
            name='asd',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
