# Generated by Django 4.0.4 on 2022-05-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse', '0005_productscategory_asd'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
