# Generated by Django 4.0.4 on 2022-05-10 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse', '0006_productslist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerse.productscategory'),
        ),
        migrations.AlterField(
            model_name='team',
            name='behance_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
    ]
